### ISSUE TITLE
Auto cleanup always keeps deleted VODs

### ISSUE THREAD

**Issue by condor125** [MrBrax/LiveStreamDVR#254]
The auto cleanup always keeps deleted VODs, even when "Keep Twitch deleted VODs" is disabled in config.
Manual cleanup works as expected.

**Comment by MrBrax** [comment]
i've seen some weird behavior, not sure how to pinpoint it though.

the log message "Cleanup old VODs for ${data_username}" shows up when it happens, does the candidate filter show anything odd?

**Comment by MSDev201** [comment]
I have a similar issue where no files are deleted.

I get this message in the logs:
```
Keeping [filename] due to it not being over storage limit (0.00 B/30.00 GB) and not being over vod limit (0/1)
```
But there are already 2 recordings of the same streamer with combined more than 30GB.
I get this message also for other streamers.

**Comment by MSDev201** [comment]
Ah okey, I see that it is ignoring the latest recording and therefore its within the limit.
So there is currently no possibility to just keep one recording and replace it every time a new recording has finished?

**Comment by MSDev201** [comment]
It works when setting the max vod count to 0. But this only works on the global setting because setting 0 on the channel vod setting makes it use the global setting.

**Comment by MrBrax** [comment]
i've rewritten it twice but still can't really understand how to handle all the cases

**Comment by MSDev201** [comment]
This works for me perfectly fine. I download all files from my public server, where I have limited storage, to my private home server where I can serve them over Jellyfin. So having set the limit of 0 globaly works for me without problems.

I think that it could work better if the total count of vods checked starts with 1, because the first vod (which was recorded) is ignored.
https://github.com/MrBrax/LiveStreamDVR/blob/b67889bae08937c058737b2acdcad30840d0ad07/server/src/Core/TwitchChannel.ts#L467

The total size would have to be increased by the size of the same last recorded vod. But I dont know where to get the value from ^^

But maybe I am overlooking something here.

**Comment by MrBrax** [comment]
i'm trying to write some tests and yeah i don't understand how this would work at all still, i'm so bad with math

**Comment by MrBrax** [comment]
ok so with a ton of tests i think it's a lot better now, but i'm still scared of vods randomly being deleted

legacy mode that only deletes one vod is still kinda broken though, but i doubt anyone but me uses it
