### ISSUE TITLE
Twitch OAuth token for Streamlink

### ISSUE THREAD

**Issue by bondurantdt** [MrBrax/LiveStreamDVR#390]
Just a quick question. I have Turbo and wanted to take advantage of the OAuth client. I got my token, but am I still supposed to put it under /data/config as twitch_oauth.txt or is it now under the capture/Twitch access token param setting? Assume I also have to put Authorization=OAuth in the Twitch API header based on https://streamlink.github.io/latest/cli/plugins/twitch.html#authentication?

**Comment by MrBrax** [comment]
Only the token string needs to be put in there, the backend takes care of the rest.

The param stuff is related to this: https://github.com/streamlink/streamlink/pull/4952

I just noticed now actually that i put the --twitch-api-header thing in twice, so yes it would work too, but I would probably not recommend doing it since access to your twitch account would be stored in the settings list. But then again it might pop up in logs too. I don't know what's best at this point.

**Comment by bondurantdt** [comment]
Makes sense and I have it working with the text file. Thanks!
