### ISSUE TITLE
Axios is not initialized. Make sure the client id and secret are set in the config.

### ISSUE THREAD

**Issue by x3r4n0** [MrBrax/LiveStreamDVR#414]
where i can set this? in the config part i dont find anything.

im using the docker-image

**Comment by MrBrax** [comment]
under config -> twitch -> first two fields

**Comment by x3r4n0** [comment]
thank you ive solved it but now i have the next problem...

i use the docker-image and add the App URL https://domain.tld:8082 after i click  "Validate external URL" i get the an error 404 Popup windows" the docker container runs on port 8082 so how i have solve this?

i get this errors after adding a channel:

djpofi is not subscribed to stream.online. Please check the config and subscribe.
djpofi is not subscribed to stream.offline. Please check the config and subscribe.
djpofi is not subscribed to channel.update. Please check the config and subscribe.

**Comment by MrBrax** [comment]
yes, you must host the server without a port number using https, a reverse proxy is the easiest way to do this

**Comment by x3r4n0** [comment]
okay i have already an container (nginx on 443) running can i use this? and what is the next step the App URL points to the (443 Server) but dosnt find the "apo/v0/hook" stuff how i add them and where i find this?

**Comment by MrBrax** [comment]
i'm not sure i fully understand but the url's are served by the server and should be accessible from the address when you test it

**Comment by x3r4n0** [comment]
can u explain the reverse proxy stuff? i have the docker image running and can access them i have already on the host nginx-reverse proxy running and point them already to my other docker images thats uses port 8443 (works and is accessable over port 443 thru the reverse proxy) but how i add the livestreamdvr to the reverse proxy ?

**Comment by MrBrax** [comment]
not really something covered by this project, i can't really give any help since i don't usually use nginx for reverse proxying

**Comment by Serph91P** [comment]
> can u explain the reverse proxy stuff? i have the docker image running and can access them i have already on the host nginx-reverse proxy running and point them already to my other docker images thats uses port 8443 (works and is accessable over port 443 thru the reverse proxy) but how i add the livestreamdvr to the reverse proxy ?

What operating system are you using. Maybe I can point you to a guide how to setup.

**Comment by btalanski** [comment]
If your Nginx reverse proxy is also in Docker, you need to make sure both the Dvr container and the Nginx container are part of a common docker network, otherwise the containers wont be able to communicate.

I'm hosting my instance using a NGINX Proxy Manager docker image. I have a domain hosted at Cloudflare, it points to my ip where I have NPM (Nginx Proxy Manager) listening on port 443. From NPM UI, I setup a proxy host pointing to my DVR container's hostname and port. So far I haven't faced any issues and setup took 5 minutes.

Give NPM a try. It's UI is pretty simple to navigate and setup new proxy hosts. Just make sure your containers all share a common network. The best way is to creata a network for NPM and add all the containers you want to proxy to that same network either with docker compose or just a regular docker cli command for running container :

docker network connect <proxy network name> <container id or name>

**Comment by Silergo** [comment]
> can u explain the reverse proxy stuff? i have the docker image running and can access them i have already on the host nginx-reverse proxy running and point them already to my other docker images thats uses port 8443 (works and is accessable over port 443 thru the reverse proxy) but how i add the livestreamdvr to the reverse proxy ?

Synology?
